# Convolutional Neural Network exercise

**We have a 5x5x1 input image and we will use 2 filters of size 3x3x1 and stride of 1**  

Write out the exact output

In [2]:
import numpy as np

In [7]:
D = [[1, 2, 1, 1, 2], \
     [1, 1, 2, 1, 1], \
     [1, 0, 1, 1, 0], \
     [0, 1, 2, 1, 1], \
     [1, 1, 0, 1, 1]]

f1 = [[0, 1, 1], \
      [1, 0, 1], \
      [1, 1, 0],]

f2 = [[0, 1, -1], \
      [0, 1, -1], \
      [-1, 1, 0],]

In [36]:
def submatrix(arr, row, col):    
    return [D[row+i][col+j] for i in range(3) for j in range(3)]
print(submatrix(D,0,0))
print([i for lst in f1 for i in lst])
#print(np.dot(submatrix(D,0,1)[:],f1[:]))

[1, 2, 1, 1, 1, 2, 1, 0, 1]
[0, 1, 1, 1, 0, 1, 1, 1, 0]


In [54]:
# iterate over range(0, (len(D) - len(filter) + 1), stride)
output1 = []
output2 = []
for row in range(0,3,1):
    for col in range(0,3,1):
        reduced_input = submatrix(D, row, col)
        filter_1 = [i for lst in f1 for i in lst]
        filter_2 = [i for lst in f2 for i in lst]
        # sanity checking ...
        #print(reduced_input)
        #print(np.dot(reduced_input,filter_1))
        #print(np.dot(reduced_input,filter_2))
        output1.append(np.dot(reduced_input,filter_1))
        output2.append(np.dot(reduced_input,filter_2))
print(np.reshape(output1, (3,3)))
print(np.reshape(output2, (3,3)))

[[7 5 8]
 [6 7 6]
 [5 5 5]]
[[-1  2 -1]
 [-1  2  0]
 [-2  0  2]]
